In [1]:
import sys

sys.path.append('../src')

In [2]:
import numpy as np

In [3]:
from Utils.utils import GetMeasurements
from Utils.cherrypick_simulations import CherryPickEquilibria

In [4]:
eq_generator = CherryPickEquilibria(
    num_agents=4,
    threshold=0.5,
    epsilon=0.1,
    num_rounds=10,
    seed=42
)

In [5]:
eq_generator.random_periodic_equilibrium(1)

On round 0 agents that go are [0 2]


array([[0, 2]])

In [6]:
period = 10
equilibrium = eq_generator.get_fair_periodic_equilibrium(period)
epsilon_equilibrium = eq_generator.apply_epsilon(equilibrium)
print('Epsilon equilibrium:')
print(epsilon_equilibrium)

Periodic equilibrium:
[[0. 0. 1. 1. 0. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0.]]
Epsilon equilibrium:
[[0. 0. 1. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 1. 1. 1. 0. 1. 1.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 0.]]


In [7]:
eq_generator.get_fair_quantities(period)

Nucleus cycle: 2.0
Fair quantity: 5
Lowest fair quantity: 4
Highest fair quantity: 5


(4, 5)

In [8]:
eq_generator.get_num_highest_payoff_players(period)

Number of highest payed players: 4


4

In [9]:
data_type = 'alternation'
num_agents=4
threshold=0.5
epsilon=0.01
eq_generator = CherryPickEquilibria(
    num_agents=num_agents,
    threshold=threshold,
    epsilon=epsilon,
    seed=42
)
eq_generator.debug = False
df_alternation = eq_generator.generate_data(data_type)
measures = ['efficiency', 'entropy', 'conditional_entropy', 'inequality']
get_m = GetMeasurements(df_alternation, measures)
get_m.get_measurements()

threshold                     id_sim  num_agents  efficiency   entropy  \
0         0.5   4-0.5-0.01-alternation-0           4    0.500000  0.498809   
1         0.5   4-0.5-0.01-alternation-1           4    0.488095  0.541781   
2         0.5  4-0.5-0.01-alternation-10           4    0.488095  0.541781   
3         0.5  4-0.5-0.01-alternation-11           4    0.500000  0.498809   
4         0.5  4-0.5-0.01-alternation-12           4    0.428571  0.580413   
..        ...                        ...         ...         ...       ...   
95        0.5  4-0.5-0.01-alternation-95           4    0.488095  0.541781   
96        0.5  4-0.5-0.01-alternation-96           4    0.488095  0.541781   
97        0.5  4-0.5-0.01-alternation-97           4    0.488095  0.545239   
98        0.5  4-0.5-0.01-alternation-98           4    0.440476  0.541781   
99        0.5  4-0.5-0.01-alternation-99           4    0.500000  0.498809   

    conditional_entropy  inequality  
0             -0.000000    0.027493  
1              0.045121    0.045592  
2              0.045121    0.045592  
3             -0.000000    0.027493  
4              0.085684    0.067344  
..                  ...         ...  
95             0.045121    0.045592  
96             0.045121    0.045592  
97             0.045121    0.023810  
98             0.045121    0.059919  
99            -0.000000    0.027493  

[100 rows x 7 columns]

In [10]:
data_type = 'segmentation'
num_agents=4
threshold=0.5
epsilon=0.01
eq_generator = CherryPickEquilibria(
    num_agents=num_agents,
    threshold=threshold,
    epsilon=epsilon,
    seed=42
)
eq_generator.debug = False
df_alternation = eq_generator.generate_data(data_type)
measures = ['efficiency', 'entropy', 'conditional_entropy', 'inequality']
get_m = GetMeasurements(df_alternation, measures)
get_m.get_measurements()

threshold                      id_sim  num_agents  efficiency   entropy  \
0         0.5   4-0.5-0.01-segmentation-0           4    0.500000 -0.000000   
1         0.5   4-0.5-0.01-segmentation-1           4    0.488095  0.069049   
2         0.5  4-0.5-0.01-segmentation-10           4    0.488095  0.069049   
3         0.5  4-0.5-0.01-segmentation-11           4    0.500000 -0.000000   
4         0.5  4-0.5-0.01-segmentation-12           4    0.500000 -0.000000   
..        ...                         ...         ...         ...       ...   
95        0.5  4-0.5-0.01-segmentation-95           4    0.500000 -0.000000   
96        0.5  4-0.5-0.01-segmentation-96           4    0.428571  0.137239   
97        0.5  4-0.5-0.01-segmentation-97           4    0.488095  0.069049   
98        0.5  4-0.5-0.01-segmentation-98           4    0.321429  0.180714   
99        0.5  4-0.5-0.01-segmentation-99           4    0.488095  0.069049   

    conditional_entropy  inequality  
0             -0.000000    0.577350  
1              0.070650    0.563939  
2              0.070650    0.563939  
3             -0.000000    0.577350  
4             -0.000000    0.577350  
..                  ...         ...  
95            -0.000000    0.577350  
96             0.069647    0.523088  
97             0.070650    0.563939  
98             0.177299    0.454049  
99             0.070650    0.563939  

[100 rows x 7 columns]

In [11]:
data_type = 'random'
num_agents=4
threshold=0.5
epsilon=0.01
eq_generator = CherryPickEquilibria(
    num_agents=num_agents,
    threshold=threshold,
    epsilon=epsilon,
    seed=42
)
eq_generator.debug = False
df_alternation = eq_generator.generate_data(data_type)
measures = ['efficiency', 'entropy', 'conditional_entropy', 'inequality']
get_m = GetMeasurements(df_alternation, measures)
get_m.get_measurements()

threshold                id_sim  num_agents  efficiency   entropy  \
0         0.5   4-0.5-0.01-random-0           4   -0.488095  0.946235   
1         0.5   4-0.5-0.01-random-1           4   -0.511905  0.883794   
2         0.5  4-0.5-0.01-random-10           4   -0.464286  0.833024   
3         0.5  4-0.5-0.01-random-11           4   -0.428571  0.865820   
4         0.5  4-0.5-0.01-random-12           4   -0.500000  0.865820   
..        ...                   ...         ...         ...       ...   
95        0.5  4-0.5-0.01-random-95           4   -0.559524  0.856833   
96        0.5  4-0.5-0.01-random-96           4   -0.488095  0.883794   
97        0.5  4-0.5-0.01-random-97           4   -0.452381  0.889630   
98        0.5  4-0.5-0.01-random-98           4   -0.416667  0.850997   
99        0.5  4-0.5-0.01-random-99           4   -0.595238  0.812365   

    conditional_entropy  inequality  
0              0.159436    0.081325  
1              0.200000    0.059919  
2              0.253308    0.071429  
3              0.218872    0.116642  
4              0.184436    0.061476  
..                  ...         ...  
95             0.203308    0.105588  
96             0.225000    0.090141  
97             0.168872    0.027493  
98             0.234436    0.081325  
99             0.250000    0.157935  

[100 rows x 7 columns]